import type { SkinDef } from './types';

// 12 skins. Nenhuma da vantagem mecanica: so paleta, forma, rastro,
// efeito ao comer, som de mordida e olho.

export const SKINS: SkinDef[] = [
  {
    id: 'osso',
    nome: 'Ossada',
    raridade: 'comum',
    preco: 0,
    acento: '#D9A441',
    cabeca: '#F0E6D2',
    cauda: '#8A7B62',
    forma: 'vertebra',
    rastro: 'poeira',
    olho: 'ponto',
    contorno: null,
    pulso: 0,
    espinha: 0.5,
    mordida: { freq: 180, tipo: 'triangle', ruido: 0.5 },
  },
  {
    id: 'brasa',
    nome: 'Brasa',
    raridade: 'comum',
    preco: 0,
    acento: '#E2703A',
    cabeca: '#F2C464',
    cauda: '#7A3B1A',
    forma: 'circulo',
    rastro: 'faisca',
    olho: 'ponto',
    contorno: null,
    pulso: 0,
    espinha: 0.62,
    mordida: { freq: 220, tipo: 'sawtooth', ruido: 0.3 },
  },
  {
    id: 'circuito',
    nome: 'Circuito',
    raridade: 'incomum',
    preco: 260,
    acento: '#4FD1A5',
    cabeca: '#7FFFD4',
    cauda: '#123A32',
    forma: 'bloco',
    rastro: 'pulso',
    olho: 'led',
    contorno: '#4FD1A5',
    pulso: 1,
    espinha: 0.7,
    mordida: { freq: 660, tipo: 'square', ruido: 0.1 },
  },
  {
    id: 'magma',
    nome: 'Magma',
    raridade: 'incomum',
    preco: 320,
    acento: '#FF6B35',
    cabeca: '#FFD166',
    cauda: '#3A0B08',
    forma: 'circulo',
    rastro: 'brasa',
    olho: 'fenda',
    contorno: null,
    pulso: 0.4,
    espinha: 0.66,
    mordida: { freq: 120, tipo: 'sawtooth', ruido: 0.6 },
  },
  {
    id: 'origami',
    nome: 'Origami',
    raridade: 'incomum',
    preco: 300,
    acento: '#E8615A',
    cabeca: '#F5EFE2',
    cauda: '#B8A98C',
    forma: 'faceta',
    rastro: 'papel',
    olho: 'cruz',
    contorno: '#8A7B62',
    pulso: 0,
    espinha: 0.42,
    mordida: { freq: 900, tipo: 'triangle', ruido: 0.9 },
  },
  {
    id: 'vidro',
    nome: 'Vidro',
    raridade: 'raro',
    preco: 620,
    acento: '#9FD8E8',
    cabeca: 'rgba(200,240,255,0.85)',
    cauda: 'rgba(120,190,215,0.35)',
    forma: 'vidro',
    rastro: 'caco',
    olho: 'anel',
    contorno: 'rgba(230,250,255,0.8)',
    pulso: 0.2,
    espinha: 0.58,
    mordida: { freq: 1400, tipo: 'sine', ruido: 0.2 },
  },
  {
    id: 'cardume',
    nome: 'Cardume',
    raridade: 'raro',
    preco: 700,
    acento: '#6EA8FF',
    cabeca: '#BBD8FF',
    cauda: '#22406E',
    forma: 'particula',
    rastro: 'cardume',
    olho: 'ponto',
    contorno: null,
    pulso: 0.6,
    espinha: 0.0,
    mordida: { freq: 520, tipo: 'sine', ruido: 0.7 },
  },
  {
    id: 'cassete',
    nome: 'Fita cassete',
    raridade: 'raro',
    preco: 740,
    acento: '#C9B037',
    cabeca: '#3A3A3A',
    cauda: '#6B5B2E',
    forma: 'fita',
    rastro: 'tinta',
    olho: 'fenda',
    contorno: '#C9B037',
    pulso: 0.3,
    espinha: 0.75,
    mordida: { freq: 300, tipo: 'square', ruido: 0.8 },
  },
  {
    id: 'musgo',
    nome: 'Musgo',
    raridade: 'incomum',
    preco: 280,
    acento: '#8FBF5A',
    cabeca: '#CDE8A0',
    cauda: '#2E4A20',
    forma: 'pilula',
    rastro: 'poeira',
    olho: 'ponto',
    contorno: null,
    pulso: 0,
    espinha: 0.6,
    mordida: { freq: 160, tipo: 'triangle', ruido: 0.6 },
  },
  {
    id: 'cobre',
    nome: 'Cobre',
    raridade: 'incomum',
    preco: 340,
    acento: '#C98B5A',
    cabeca: '#EBB07A',
    cauda: '#5A3520',
    forma: 'vertebra',
    rastro: 'faisca',
    olho: 'anel',
    contorno: '#8A5A34',
    pulso: 0.5,
    espinha: 0.5,
    mordida: { freq: 420, tipo: 'sawtooth', ruido: 0.25 },
  },
  {
    id: 'vazio',
    nome: 'Vazio',
    raridade: 'lendario',
    preco: 1400,
    acento: '#FFFFFF',
    cabeca: '#050505',
    cauda: '#0B0B0B',
    forma: 'circulo',
    rastro: 'sombra',
    olho: 'vazio',
    contorno: '#FFFFFF',
    pulso: 0,
    espinha: 0.68,
    mordida: { freq: 70, tipo: 'sine', ruido: 0.15 },
  },
  {
    id: 'aurora',
    nome: 'Aurora',
    raridade: 'lendario',
    preco: 1800,
    acento: '#B78BFF',
    cabeca: '#D8F6FF',
    cauda: '#4A2B8A',
    forma: 'vidro',
    rastro: 'pulso',
    olho: 'led',
    contorno: 'rgba(200,170,255,0.7)',
    pulso: 1,
    espinha: 0.6,
    mordida: { freq: 780, tipo: 'sine', ruido: 0.1 },
  },
];

export function skinById(id: string): SkinDef {
  for (const s of SKINS) if (s.id === id) return s;
  return SKINS[0];
}
